In [1]:
%%capture
%pip install praw
%pip install psaw

In [2]:
import pandas as pd 
import numpy as np 
import praw 
from psaw import PushshiftAPI 
import datetime as dt

In [3]:
# https://towardsdatascience.com/scraping-reddit-data-1c0af3040768
# https://praw.readthedocs.io/en/latest/ 
# https://pypi.org/project/psaw/
# Retrieve reddit client with api key login and a follow up of data retrieval 
# to use PSAW
api = PushshiftAPI()
reddit = praw.Reddit(client_id='jt4hWsKS8poo7txQtBXSAw',
                     client_secret='CRteJYmAtXXSZNAPRqVcdMHQsAOlqQ',
                     user_agent='Quantliop_data')

# NIKE

In [4]:
import datetime as dt

start_epoch=int(dt.datetime(2022, 8, 1).timestamp())
after_epoch = int(dt.datetime(2022, 9, 30).timestamp())


api_request_generator = api.search_submissions(q='Nike',after = start_epoch, num_comments = ">1",before=after_epoch,filter=['url', 'title', 'subreddit','id','score','num_comments', 'created_utc', 'score', 'ID'])
Nike_submission = pd.DataFrame([submission.d_ for submission in api_request_generator])

In [5]:

# Nike_submission["time"] = pd.to_datetime(Nike_submission['created_utc'],  unit='s')

In [6]:
Nike_submission

,created_utc,id,num_comments,score,subreddit,title,url,created
0,1664502300,xrp0ge,2,1,repbudgetsneakers,¥210 Nike Dunk Low UNC VT Batch from philanthr...,https://shop1372944448.v.weidian.com/item.html...,1.664520e+09
1,1664490472,xrkx0w,2,1,appleswap,[USA-AZ] [H] Apple watch series 3 42mm space g...,https://www.reddit.com/r/appleswap/comments/xr...,1.664508e+09
2,1664475300,xrewfl,2,1,wallstreetbets,Everyone in the world has been jumping on the ...,https://i.redd.it/is9lykx3auq91.jpg,1.664493e+09
3,1664404638,xqqnyp,2,1,wallstreetbets,How are my fellow regards feeling about this N...,https://i.redd.it/505f1bzzfoq91.jpg,1.664423e+09
4,1664390637,xqkrj9,2,1,sneakermarket,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,https://imgur.com/a/d6SWW73,1.664409e+09
...,...,...,...,...,...,...,...,...
368,1659383886,wdqtzn,2,1,giftcardexchange,[H] $75 nike giftcard [W] $65 paypal friends a...,https://www.reddit.com/r/giftcardexchange/comm...,1.659402e+09
369,1659355263,wdfq5o,2,1,repbudgetsneakers,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",https://weidian.com/item.html?itemID=491253535...,1.659373e+09
370,1659345912,wdd0dt,2,1,repbudgetsneakers,[QC] Nike Air foce 1 x travis fossil OWF for 3...,https://weidian.com/item.html?itemID=432491750...,1.659364e+09
371,1659337997,wdaza8,2,1,repbudgetsneakers,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,https://www.reddit.com/gallery/wdaza8,1.659356e+09
372,1659336226,wdai08,3,1,repbudgetsneakers,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,https://www.reddit.com/r/repbudgetsneakers/com...,1.659354e+09

In [7]:
%%capture

post = []
Subreddit = []
Title = []
post_URL = []
comments = []
date = []
for index, row in Nike_submission.iterrows():
    post_id = row["id"]
    submission = reddit.submission(id=post_id)
    try:
      for top_level_comment in submission.comments:
        if top_level_comment.body is not None:
          Title.append(row["title"])
          post_URL.append(row["url"])
          Subreddit.append(row["subreddit"])
          post.append(post_id)
          comments.append(top_level_comment.body)
          date.append(pd.to_datetime(row["created_utc"], unit = "s"))
          # date.append(row["time"])
    except:
      print("Banned on " + str(post_id))

In [8]:
comments

[]

In [9]:
post

['xrp0ge',
 'xrkx0w',
 'xrewfl',
 'xqqnyp',
 'xqkrj9',
 'xqgun5',
 'xpvjl0',
 'xpm2n0',
 'xp2aic',
 'xot6bc',
 'xos9hc',
 'xopql4',
 'xooehj',
 'xoav13',
 'xntuci',
 'xnhxdy',
 'xn5fi7',
 'xmfl5m',
 'xmevj4',
 'xme0a6',
 'xm9h58',
 'xlzodm',
 'xlxm0m',
 'xlwn55',
 'xlv7pl',
 'xlpoii',
 'xlh62t',
 'xlae2f',
 'xkwq3i',
 'xkwaix',
 'xkv6bp',
 'xkox5n',
 'xkouz7',
 'xknbfa',
 'xklg6r',
 'xjyx0o',
 'xjynhv',
 'xjuhne',
 'xjop9w',
 'xjkdkq',
 'xjkdfr',
 'xjkd8o',
 'xjkcxk',
 'xjkcr3',
 'xjkcjl',
 'xjkccq',
 'xj6hx7',
 'xj6hsj',
 'xj6hnp',
 'xj6h0o',
 'xj6gqm',
 'xisltf',
 'xirxv3',
 'xiova5',
 'xim5n5',
 'xidzsp',
 'xidxgz',
 'xhvkaq',
 'xhv1lk',
 'xhs9vg',
 'xhf65x',
 'xh8zk6',
 'xh8uck',
 'xh7g7o',
 'xgzg1q',
 'xgokzp',
 'xgj3x1',
 'xgg6ui',
 'xgfxjw',
 'xfy3cq',
 'xfsf0y',
 'xfqbrn',
 'xfnm25',
 'xfninx',
 'xffeuv',
 'xfbble',
 'xf5ibr',
 'xf11mg',
 'xes5j4',
 'xekt6o',
 'xehibd',
 'xefbra',
 'xecicq',
 'xearbj',
 'xe91cs',
 'xe5omy',
 'xe2l5m',
 'xe0mww',
 'xdzuei',
 'xde2aa',
 'xdaj3s',
 'xd9skb',
 'xd73yu',
 'xd6li3',
 'xd6fqa',
 'xd5iws',
 'xd46wr',
 'xd34b4',
 'xd1rd2',
 'xbz059',
 'xbt192',
 'xbqitl',
 'xbknjb',
 'xbi798',
 'xbi69c',
 'xb21pm',
 'xb14c1',
 'xaswtc',
 'xanaba',
 'xamqnr',
 'xah8n5',
 'xa5d4i',
 'xa4myv',
 'xa4ju7',
 'xa4glv',
 'x9zjrl',
 'x9s2xr',
 'x9s2k8',
 'x9ioh9',
 'x98l9y',
 'x98gxt',
 'x8zuh9',
 'x8z8q6',
 'x8te6o',
 'x8jo2i',
 'x8hfoz',
 'x8fbz3',
 'x8dtmn',
 'x84ix2',
 'x80dkp',
 'x80ad2',
 'x7nlwo',
 'x7n77x',
 'x7c1x2',
 'x7b18n',
 'x78j1h',
 'x76fr9',
 'x75g8o',
 'x74bm4',
 'x7445z',
 'x742rf',
 'x737qb',
 'x6qadw',
 'x6kg2f',
 'x6hltp',
 'x605yb',
 'x5z60b',
 'x5z4hn',
 'x5t2l1',
 'x5swqf',
 'x5qscj',
 'x5pib3',
 'x5p960',
 'x5nivv',
 'x5jmeq',
 'x5ib0x',
 'x5heha',
 'x5hb3s',
 'x5ca8p',
 'x52fwx',
 'x4r71i',
 'x4orde',
 'x4o8a1',
 'x4n99v',
 'x4lzqw',
 'x45wdc',
 'x3v3yf',
 'x3sh1e',
 'x3sdrj',
 'x3s9dh',
 'x3oibo',
 'x3hn1w',
 'x33242',
 'x316mx',
 'x3028t',
 'x2h6k9',
 'x2eu9y',
 'x20d6f',
 'x209wh',
 'x1tvua',
 'x1rlo2',
 'x1rg2l',
 'x1r42f',
 'x1qpvv',
 'x1l9sh',
 'x1es7b',
 'x17l3p',
 'x16zzi',
 'x14w8n',
 'x0lmyd',
 'x0ejd6',
 'x066uf',
 'x065ia',
 'x034ex',
 'x01v6v',
 'x01sc0',
 'wzxpyj',
 'wzvvrn',
 'wzu481',
 'wz81sx',
 'wywll2',
 'wyweb1',
 'wysy78',
 'wyo73q',
 'wylwcq',
 'wy96bj',
 'wy8vvs',
 'wy8i2j',
 'wy4ge2',
 'wy45yq',
 'wxzbqe',
 'wxut4a',
 'wxpi9x',
 'wxo1ie',
 'wxkb97',
 'wxgirh',
 'wxd8r5',
 'wxcy3s',
 'wx6wqf',
 'wx3mjw',
 'wx2gop',
 'wwz507',
 'wwipgr',
 'wwai65',
 'wvv1m0',
 'wvux7m',
 'wvr8tn',
 'wvpng5',
 'wvhr42',
 'wvheg4',
 'wvc5tn',
 'wvate0',
 'wv4yfr',
 'wv1ivf',
 'wuxvvf',
 'wuv54p',
 'wuqhxq',
 'wu9jp8',
 'wu8yms',
 'wu8j20',
 'wu8g0h',
 'wu7x1x',
 'wu4yur',
 'wu14v0',
 'wu13l5',
 'wt7ed8',
 'wsqjlm',
 'wsqggh',
 'wsofqy',
 'wsjl71',
 'wsjhnm',
 'wshq5i',
 'wsebks',
 'ws68pf',
 'wrwh1a',
 'wrtf3v',
 'wrp3ej',
 'wribqi',
 'wrfbat',
 'wrf95s',
 'wr8zd1',
 'wr235o',
 'wr0mkv',
 'wr0iow',
 'wqyfbv',
 'wqyb5g',
 'wqu548',
 'wqrcw1',
 'wqplmi',
 'wqpgvj',
 'wqnsv5',
 'wqnfw4',
 'wqkgdl',
 'wq9yl5',
 'wq7kj2',
 'wpvfxo',
 'wpchr3',
 'woujhp',
 'wokcgg',
 'wohs6y',
 'woc4ro',
 'woc1c7',
 'wo7wta',
 'wo7bri',
 'wo604i',
 'wo0zup',
 'wo0n4r',
 'wnxw92',
 'wnwno1',
 'wngchv',
 'wndn9t',
 'wnb2s0',
 'wnakas',
 'wna4vx',
 'wmxc5b',
 'wmrnjy',
 'wmqwwi',
 'wmh0u2',
 'wmg6l4',
 'wm85pc',
 'wluu0m',
 'wlj8y5',
 'wlh4n3',
 'wkjtuw',
 'wjya6o',
 'wjumcy',
 'wjsxib',
 'wjpafo',
 'wjofdn',
 'wjk9b3',
 'wjhhcv',
 'wjhfdf',
 'wjd03d',
 'wj7s3n',
 'wj77yn',
 'wj76d5',
 'wj4rh5',
 'wj4ppr',
 'wj0dav',
 'winbo8',
 'wij785',
 'wih3mc',
 'wi7grg',
 'whud2c',
 'wh3qj0',
 'wh3nhl',
 'wh38w2',
 'wgrw01',
 'wgnw1y',
 'wgmb4o',
 'wgdptz',
 'wgad8q',
 'wg7q6b',
 'wg7llx',
 'wg7lhx',
 'wg7hmr',
 'wg7g0m',
 'wg798y',
 'wg76gu',
 'wg6xbc',
 'wg6nrp',
 'wg6l7r',
 'wg6hs3',
 'wg3ygx',
 'wg2a59',
 'wfxiac',
 'wfwrs6',
 'wfuh3b',
 'wfnxi0',
 'wfkjua',
 'wfeegn',
 'wfba94',
 'wf5g70',
 'wf4eo0',
 'wf46r3',
 'wf33cd',
 'weqo0n',
 'wepupl',
 'wept05',
 'wenvjx',
 'wel0c9',
 'wektlz',
 'wej2c9',
 'weao3d',
 'weaeh2',
 'we8pc6',
 'we68ii',
 'wdwibj',
 'wdqtzn',
 'wdfq5o',
 'wdd0dt',
 'wdaza8',
 'wdai08']

In [10]:
comments = [d for d in comments if not d.startswith('Your post has been removed')]
comments = [d for d in comments if not d.startswith('Your [submission](')]
comments = pd.Series(comments)
post = pd.Series(post)
Nike_final = pd.DataFrame(
    {'Title': Title,
     'Subreddit': Subreddit,
     'Post ID': post,
     'Post URL': post_URL,
     'Comments': comments,
     'Date':date
    })


Nike_final

C:\Users\cjong\AppData\Local\Temp\ipykernel_33988\351757558.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  comments = pd.Series(comments)

,Title,Subreddit,Post ID,Post URL,Comments,Date
0,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN,2022-09-30 01:45:00
1,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN,2022-09-29 22:27:52
2,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN,2022-09-29 18:15:00
3,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN,2022-09-28 22:37:18
4,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN,2022-09-28 18:43:57
...,...,...,...,...,...,...
368,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN,2022-08-01 19:58:06
369,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN,2022-08-01 12:01:03
370,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN,2022-08-01 09:25:12
371,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN,2022-08-01 07:13:17
372,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN,2022-08-01 06:43:46

In [11]:
Nike_final.to_csv('Nike Keyword Method.csv')

In [12]:
Nike_final["Post ID"].unique()

array(['xrp0ge', 'xrkx0w', 'xrewfl', 'xqqnyp', 'xqkrj9', 'xqgun5',
       'xpvjl0', 'xpm2n0', 'xp2aic', 'xot6bc', 'xos9hc', 'xopql4',
       'xooehj', 'xoav13', 'xntuci', 'xnhxdy', 'xn5fi7', 'xmfl5m',
       'xmevj4', 'xme0a6', 'xm9h58', 'xlzodm', 'xlxm0m', 'xlwn55',
       'xlv7pl', 'xlpoii', 'xlh62t', 'xlae2f', 'xkwq3i', 'xkwaix',
       'xkv6bp', 'xkox5n', 'xkouz7', 'xknbfa', 'xklg6r', 'xjyx0o',
       'xjynhv', 'xjuhne', 'xjop9w', 'xjkdkq', 'xjkdfr', 'xjkd8o',
       'xjkcxk', 'xjkcr3', 'xjkcjl', 'xjkccq', 'xj6hx7', 'xj6hsj',
       'xj6hnp', 'xj6h0o', 'xj6gqm', 'xisltf', 'xirxv3', 'xiova5',
       'xim5n5', 'xidzsp', 'xidxgz', 'xhvkaq', 'xhv1lk', 'xhs9vg',
       'xhf65x', 'xh8zk6', 'xh8uck', 'xh7g7o', 'xgzg1q', 'xgokzp',
       'xgj3x1', 'xgg6ui', 'xgfxjw', 'xfy3cq', 'xfsf0y', 'xfqbrn',
       'xfnm25', 'xfninx', 'xffeuv', 'xfbble', 'xf5ibr', 'xf11mg',
       'xes5j4', 'xekt6o', 'xehibd', 'xefbra', 'xecicq', 'xearbj',
       'xe91cs', 'xe5omy', 'xe2l5m', 'xe0mww', 'xdzuei', 'xde2aa',
       'xdaj3s', 'xd9skb', 'xd73yu', 'xd6li3', 'xd6fqa', 'xd5iws',
       'xd46wr', 'xd34b4', 'xd1rd2', 'xbz059', 'xbt192', 'xbqitl',
       'xbknjb', 'xbi798', 'xbi69c', 'xb21pm', 'xb14c1', 'xaswtc',
       'xanaba', 'xamqnr', 'xah8n5', 'xa5d4i', 'xa4myv', 'xa4ju7',
       'xa4glv', 'x9zjrl', 'x9s2xr', 'x9s2k8', 'x9ioh9', 'x98l9y',
       'x98gxt', 'x8zuh9', 'x8z8q6', 'x8te6o', 'x8jo2i', 'x8hfoz',
       'x8fbz3', 'x8dtmn', 'x84ix2', 'x80dkp', 'x80ad2', 'x7nlwo',
       'x7n77x', 'x7c1x2', 'x7b18n', 'x78j1h', 'x76fr9', 'x75g8o',
       'x74bm4', 'x7445z', 'x742rf', 'x737qb', 'x6qadw', 'x6kg2f',
       'x6hltp', 'x605yb', 'x5z60b', 'x5z4hn', 'x5t2l1', 'x5swqf',
       'x5qscj', 'x5pib3', 'x5p960', 'x5nivv', 'x5jmeq', 'x5ib0x',
       'x5heha', 'x5hb3s', 'x5ca8p', 'x52fwx', 'x4r71i', 'x4orde',
       'x4o8a1', 'x4n99v', 'x4lzqw', 'x45wdc', 'x3v3yf', 'x3sh1e',
       'x3sdrj', 'x3s9dh', 'x3oibo', 'x3hn1w', 'x33242', 'x316mx',
       'x3028t', 'x2h6k9', 'x2eu9y', 'x20d6f', 'x209wh', 'x1tvua',
       'x1rlo2', 'x1rg2l', 'x1r42f', 'x1qpvv', 'x1l9sh', 'x1es7b',
       'x17l3p', 'x16zzi', 'x14w8n', 'x0lmyd', 'x0ejd6', 'x066uf',
       'x065ia', 'x034ex', 'x01v6v', 'x01sc0', 'wzxpyj', 'wzvvrn',
       'wzu481', 'wz81sx', 'wywll2', 'wyweb1', 'wysy78', 'wyo73q',
       'wylwcq', 'wy96bj', 'wy8vvs', 'wy8i2j', 'wy4ge2', 'wy45yq',
       'wxzbqe', 'wxut4a', 'wxpi9x', 'wxo1ie', 'wxkb97', 'wxgirh',
       'wxd8r5', 'wxcy3s', 'wx6wqf', 'wx3mjw', 'wx2gop', 'wwz507',
       'wwipgr', 'wwai65', 'wvv1m0', 'wvux7m', 'wvr8tn', 'wvpng5',
       'wvhr42', 'wvheg4', 'wvc5tn', 'wvate0', 'wv4yfr', 'wv1ivf',
       'wuxvvf', 'wuv54p', 'wuqhxq', 'wu9jp8', 'wu8yms', 'wu8j20',
       'wu8g0h', 'wu7x1x', 'wu4yur', 'wu14v0', 'wu13l5', 'wt7ed8',
       'wsqjlm', 'wsqggh', 'wsofqy', 'wsjl71', 'wsjhnm', 'wshq5i',
       'wsebks', 'ws68pf', 'wrwh1a', 'wrtf3v', 'wrp3ej', 'wribqi',
       'wrfbat', 'wrf95s', 'wr8zd1', 'wr235o', 'wr0mkv', 'wr0iow',
       'wqyfbv', 'wqyb5g', 'wqu548', 'wqrcw1', 'wqplmi', 'wqpgvj',
       'wqnsv5', 'wqnfw4', 'wqkgdl', 'wq9yl5', 'wq7kj2', 'wpvfxo',
       'wpchr3', 'woujhp', 'wokcgg', 'wohs6y', 'woc4ro', 'woc1c7',
       'wo7wta', 'wo7bri', 'wo604i', 'wo0zup', 'wo0n4r', 'wnxw92',
       'wnwno1', 'wngchv', 'wndn9t', 'wnb2s0', 'wnakas', 'wna4vx',
       'wmxc5b', 'wmrnjy', 'wmqwwi', 'wmh0u2', 'wmg6l4', 'wm85pc',
       'wluu0m', 'wlj8y5', 'wlh4n3', 'wkjtuw', 'wjya6o', 'wjumcy',
       'wjsxib', 'wjpafo', 'wjofdn', 'wjk9b3', 'wjhhcv', 'wjhfdf',
       'wjd03d', 'wj7s3n', 'wj77yn', 'wj76d5', 'wj4rh5', 'wj4ppr',
       'wj0dav', 'winbo8', 'wij785', 'wih3mc', 'wi7grg', 'whud2c',
       'wh3qj0', 'wh3nhl', 'wh38w2', 'wgrw01', 'wgnw1y', 'wgmb4o',
       'wgdptz', 'wgad8q', 'wg7q6b', 'wg7llx', 'wg7lhx', 'wg7hmr',
       'wg7g0m', 'wg798y', 'wg76gu', 'wg6xbc', 'wg6nrp', 'wg6l7r',
       'wg6hs3', 'wg3ygx', 'wg2a59', 'wfxiac', 'wfwrs6', 'wfuh3b',
       'wfnxi0', 'wfkjua', 'wfeegn', 'wfba94', 'wf5g70', 'wf4eo0',
       'wf46r3', 'wf33cd', 'weqo0n', 'wepupl', 'wept05', 'wenvjx',
       'wel0c9', 'wektlz', 'wej2c9', 'weao3d', 'weaeh2', 'we8pc6',
       'we68ii', 'wdwibj', 'wdqtzn', 'wdfq5o', 'wdd0dt', 'wdaza8',
       'wdai08'], dtype=object)

# Adidas

In [13]:
import datetime as dt

start_epoch=int(dt.datetime(2022, 8, 1).timestamp())
after_epoch = int(dt.datetime(2022, 9, 30).timestamp())


api_request_generator = api.search_submissions(q='Adidas',after = start_epoch, num_comments = ">1",before=after_epoch,filter=['url', 'title', 'subreddit','id','score','num_comments', 'created_utc', 'score', 'ID'])
Adidas_submission = pd.DataFrame([submission.d_ for submission in api_request_generator])

In [14]:
Adidas_submission

,created_utc,id,num_comments,score,subreddit,title,url,created
0,1664480732,xrh4au,2,1,giftcardexchange,[H] $19 Adidas Gift Card [W] 80% Paypal,https://www.reddit.com/r/giftcardexchange/comm...,1.664499e+09
1,1664266000,xpafpz,2,1,giftcardexchange,[H] $20 Tango Giftcard (10+10) [W] INR1340 UPI,https://www.reddit.com/r/giftcardexchange/comm...,1.664284e+09
2,1664202441,xoktw7,2,1,repbudgetsneakers,160 + 10 ¥ Adidas Yeezy 350 V2 Black and Red /...,https://www.reddit.com/gallery/xoktw7,1.664220e+09
3,1664201629,xokh2x,2,1,repbudgetsneakers,Help me QC this Adidas yeezy 350 tail light fo...,https://shop1250671711.v.weidian.com/item.html...,1.664220e+09
4,1664144162,xo0sr3,2,1,giftcardexchange,[H] $50 Adidas Gift Card [W] 70% Paypal,https://www.reddit.com/r/giftcardexchange/comm...,1.664162e+09
...,...,...,...,...,...,...,...,...
66,1659706468,wgvn02,2,1,sneakermarket,[WTS] adidas Yeezy Slide Bone FZ5897 [US9],https://imgur.com/a/TOz6eIS,1.659724e+09
67,1659691459,wgqu8h,2,1,repbudgetsneakers,[QC] ¥160 Adidas Yeezy Boost 350 V2 Zebra + lo...,https://www.reddit.com/gallery/wgqu8h,1.659709e+09
68,1659531386,wf5wyu,2,1,repbudgetsneakers,[QC] ¥160+10 adidas Yeezy Boost 350 V2 Onyx • ...,https://www.reddit.com/gallery/wf5wyu,1.659549e+09
69,1659513780,wf0lub,2,1,ChavGirls,Love my adidas 🍑🍭,https://i.redd.it/ekvkioryggf91.jpg,1.659532e+09
70,1659460369,wehb30,2,1,sneakermarket,[WTS] adidas Yeezy Slide Bone FZ5897 [US9],https://imgur.com/a/TOz6eIS,1.659478e+09

In [15]:
%%capture

post = []
Subreddit = []
Title = []
post_URL = []
comments = []
date = []
for index, row in Nike_submission.iterrows():
    post_id = row["id"]
    submission = reddit.submission(id=post_id)
    try:
      for top_level_comment in submission.comments:
        if top_level_comment.body is not None:
          Title.append(row["title"])
          post_URL.append(row["url"])
          Subreddit.append(row["subreddit"])
          post.append(post_id)
          comments.append(top_level_comment.body)
          date.append(pd.to_datetime(row["created_utc"], unit = "s"))
          # date.append(row["time"])
    except:
      print("Banned on " + str(post_id))

In [16]:
comments = [d for d in comments if not d.startswith('Your post has been removed')]
comments = [d for d in comments if not d.startswith('Your [submission](')]
comments = pd.Series(comments)
post = pd.Series(post)
Adidas_final = pd.DataFrame(
    {'Date': date,
     'Title': Title,
     'Subreddit': Subreddit,
     'Post ID': post,
     'Post URL': post_URL,
     'Comments': comments
    })


Adidas_final

C:\Users\cjong\AppData\Local\Temp\ipykernel_33988\3884302193.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  comments = pd.Series(comments)

,Date,Title,Subreddit,Post ID,Post URL,Comments
0,2022-09-30 01:45:00,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN
1,2022-09-29 22:27:52,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN
2,2022-09-29 18:15:00,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN
3,2022-09-28 22:37:18,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN
4,2022-09-28 18:43:57,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN
...,...,...,...,...,...,...
368,2022-08-01 19:58:06,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN
369,2022-08-01 12:01:03,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN
370,2022-08-01 09:25:12,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN
371,2022-08-01 07:13:17,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN
372,2022-08-01 06:43:46,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN

In [17]:
Adidas_final.to_csv('Adidas Keyword Method.csv')

In [18]:
start_epoch=int(dt.datetime(2022, 8, 1).timestamp())
after_epoch = int(dt.datetime(2022, 9, 30).timestamp())


api_request_generator = api.search_submissions(q='Converse',after = start_epoch, num_comments = ">1",before=after_epoch,filter=['url', 'title', 'subreddit','id','score','num_comments', 'created_utc', 'score', 'ID'])
Converse_submission = pd.DataFrame([submission.d_ for submission in api_request_generator])

In [19]:
%%capture

post = []
Subreddit = []
Title = []
post_URL = []
comments = []
date = []
for index, row in Nike_submission.iterrows():
    post_id = row["id"]
    submission = reddit.submission(id=post_id)
    try:
      for top_level_comment in submission.comments:
        if top_level_comment.body is not None:
          Title.append(row["title"])
          post_URL.append(row["url"])
          Subreddit.append(row["subreddit"])
          post.append(post_id)
          comments.append(top_level_comment.body)
          date.append(pd.to_datetime(row["created_utc"], unit = "s"))
          # date.append(row["time"])
    except:
      print("Banned on " + str(post_id))

In [20]:
comments = [d for d in comments if not d.startswith('Your post has been removed')]
comments = [d for d in comments if not d.startswith('Your [submission](')]
comments = pd.Series(comments)
post = pd.Series(post)
Converse_final = pd.DataFrame(
    {'Date':date,
     'Title': Title,
     'Subreddit': Subreddit,
     'Post ID': post,
     'Post URL': post_URL,
     'Comments': comments
    })


Converse_final

C:\Users\cjong\AppData\Local\Temp\ipykernel_33988\2154150975.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  comments = pd.Series(comments)

,Date,Title,Subreddit,Post ID,Post URL,Comments
0,2022-09-30 01:45:00,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN
1,2022-09-29 22:27:52,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN
2,2022-09-29 18:15:00,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN
3,2022-09-28 22:37:18,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN
4,2022-09-28 18:43:57,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN
...,...,...,...,...,...,...
368,2022-08-01 19:58:06,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN
369,2022-08-01 12:01:03,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN
370,2022-08-01 09:25:12,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN
371,2022-08-01 07:13:17,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN
372,2022-08-01 06:43:46,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN

In [21]:
Converse_final.to_csv("Converse Final.csv")

In [22]:
start_epoch=int(dt.datetime(2022, 8, 1).timestamp())
after_epoch = int(dt.datetime(2022, 9, 30).timestamp())


api_request_generator = api.search_submissions(q='Reebok',after = start_epoch, num_comments = ">1",before=after_epoch,filter=['url', 'title', 'subreddit','id','score','num_comments', 'created_utc', 'score', 'ID'])
Reebok_submission = pd.DataFrame([submission.d_ for submission in api_request_generator])

In [23]:
%%capture

post = []
Subreddit = []
Title = []
post_URL = []
comments = []
date = []
for index, row in Nike_submission.iterrows():
    post_id = row["id"]
    submission = reddit.submission(id=post_id)
    try:
      for top_level_comment in submission.comments:
        if top_level_comment.body is not None:
          Title.append(row["title"])
          post_URL.append(row["url"])
          Subreddit.append(row["subreddit"])
          post.append(post_id)
          comments.append(top_level_comment.body)
          date.append(pd.to_datetime(row["created_utc"], unit = "s"))
          # date.append(row["time"])
    except:
      print("Banned on " + str(post_id))

In [24]:
comments = [d for d in comments if not d.startswith('Your post has been removed')]
comments = [d for d in comments if not d.startswith('Your [submission](')]
comments = pd.Series(comments)
post = pd.Series(post)
Reebok_final = pd.DataFrame(
    {'Date':date,
     'Title': Title,
     'Subreddit': Subreddit,
     'Post ID': post,
     'Post URL': post_URL,
     'Comments': comments
    })


Reebok_final

C:\Users\cjong\AppData\Local\Temp\ipykernel_33988\3356379009.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  comments = pd.Series(comments)

,Date,Title,Subreddit,Post ID,Post URL,Comments
0,2022-09-30 01:45:00,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN
1,2022-09-29 22:27:52,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN
2,2022-09-29 18:15:00,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN
3,2022-09-28 22:37:18,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN
4,2022-09-28 18:43:57,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN
...,...,...,...,...,...,...
368,2022-08-01 19:58:06,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN
369,2022-08-01 12:01:03,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN
370,2022-08-01 09:25:12,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN
371,2022-08-01 07:13:17,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN
372,2022-08-01 06:43:46,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN

In [25]:
Reebok_final.to_csv('Reebok Keyword Method.csv')

In [26]:
start_epoch=int(dt.datetime(2022, 8, 1).timestamp())
after_epoch = int(dt.datetime(2022, 9, 30).timestamp())


api_request_generator = api.search_submissions(q='New Balance',after = start_epoch, num_comments = ">1",before=after_epoch,filter=['url', 'title', 'subreddit','id','score','num_comments', 'created_utc', 'score', 'ID'])
NB_submission = pd.DataFrame([submission.d_ for submission in api_request_generator])

In [27]:
%%capture

post = []
Subreddit = []
Title = []
post_URL = []
comments = []
date = []
for index, row in Nike_submission.iterrows():
    post_id = row["id"]
    submission = reddit.submission(id=post_id)
    try:
      for top_level_comment in submission.comments:
        if top_level_comment.body is not None:
          Title.append(row["title"])
          post_URL.append(row["url"])
          Subreddit.append(row["subreddit"])
          post.append(post_id)
          comments.append(top_level_comment.body)
          date.append(pd.to_datetime(row["created_utc"], unit = "s"))
          # date.append(row["time"])
    except:
      print("Banned on " + str(post_id))

In [28]:
comments = [d for d in comments if not d.startswith('Your post has been removed')]
comments = [d for d in comments if not d.startswith('Your [submission](')]
comments = pd.Series(comments)
post = pd.Series(post)
NB_final = pd.DataFrame(
    {'Date': date,
     'Title': Title,
     'Subreddit': Subreddit,
     'Post ID': post,
     'Post URL': post_URL,
     'Comments': comments
    })


NB_final

C:\Users\cjong\AppData\Local\Temp\ipykernel_33988\3065669805.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  comments = pd.Series(comments)

,Date,Title,Subreddit,Post ID,Post URL,Comments
0,2022-09-30 01:45:00,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN
1,2022-09-29 22:27:52,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN
2,2022-09-29 18:15:00,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN
3,2022-09-28 22:37:18,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN
4,2022-09-28 18:43:57,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN
...,...,...,...,...,...,...
368,2022-08-01 19:58:06,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN
369,2022-08-01 12:01:03,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN
370,2022-08-01 09:25:12,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN
371,2022-08-01 07:13:17,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN
372,2022-08-01 06:43:46,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN

In [29]:
NB_final.to_csv("NB Final.csv")

# Coalescing shoe brands into sentiment_score.csv

In [30]:
Nike_final["text"] = Nike_final["Comments"]
Adidas_final["text"] = Adidas_final["Comments"]
Converse_final["text"] = Converse_final["Comments"]
Reebok_final["text"] = Reebok_final["Comments"]
NB_final["text"] = NB_final["Comments"]

In [31]:
Nike_final["created_at"] = Nike_final["Date"]
Adidas_final["created_at"] = Adidas_final["Date"]
Converse_final["created_at"] = Converse_final["Date"]
Reebok_final["created_at"] = Reebok_final["Date"]
NB_final["created_at"] = NB_final["Date"]

In [32]:
Nike_final["brand"] = "nike"
Adidas_final["brand"] = "adidas"
Converse_final["brand"] = "converse"
Reebok_final["brand"] = "reebok"
NB_final["brand"] = "newbalance"

In [33]:
pdlist = [Nike_final, Adidas_final, Converse_final, Reebok_final, NB_final]


sentiment_score_df = pd.concat(pdlist)

In [34]:
sentiment_score_df

,Title,Subreddit,Post ID,Post URL,Comments,Date,text,created_at,brand
0,¥210 Nike Dunk Low UNC VT Batch from philanthr...,repbudgetsneakers,xrp0ge,https://shop1372944448.v.weidian.com/item.html...,NaN,2022-09-30 01:45:00,NaN,2022-09-30 01:45:00,nike
1,[USA-AZ] [H] Apple watch series 3 42mm space g...,appleswap,xrkx0w,https://www.reddit.com/r/appleswap/comments/xr...,NaN,2022-09-29 22:27:52,NaN,2022-09-29 22:27:52,nike
2,Everyone in the world has been jumping on the ...,wallstreetbets,xrewfl,https://i.redd.it/is9lykx3auq91.jpg,NaN,2022-09-29 18:15:00,NaN,2022-09-29 18:15:00,nike
3,How are my fellow regards feeling about this N...,wallstreetbets,xqqnyp,https://i.redd.it/505f1bzzfoq91.jpg,NaN,2022-09-28 22:37:18,NaN,2022-09-28 22:37:18,nike
4,[WTS] NIKE Off White Jordan 1 UNC 10.5 $2000 -...,sneakermarket,xqkrj9,https://imgur.com/a/d6SWW73,NaN,2022-09-28 18:43:57,NaN,2022-09-28 18:43:57,nike
...,...,...,...,...,...,...,...,...,...
368,[H] $75 nike giftcard [W] $65 paypal friends a...,giftcardexchange,wdqtzn,https://www.reddit.com/r/giftcardexchange/comm...,NaN,2022-08-01 19:58:06,NaN,2022-08-01 19:58:06,newbalance
369,"(QC) Nike Dunk Low Michigan State, 179 ¥, Xiao...",repbudgetsneakers,wdfq5o,https://weidian.com/item.html?itemID=491253535...,NaN,2022-08-01 12:01:03,NaN,2022-08-01 12:01:03,newbalance
370,[QC] Nike Air foce 1 x travis fossil OWF for 3...,repbudgetsneakers,wdd0dt,https://weidian.com/item.html?itemID=432491750...,NaN,2022-08-01 09:25:12,NaN,2022-08-01 09:25:12,newbalance
371,(Qc) Nike dunk light bone (VT batch) - 200 ¥ -...,repbudgetsneakers,wdaza8,https://www.reddit.com/gallery/wdaza8,NaN,2022-08-01 07:13:17,NaN,2022-08-01 07:13:17,newbalance
372,190¥ Nike Dunk OW Lot 36 Pandabuy-Qc,repbudgetsneakers,wdai08,https://www.reddit.com/r/repbudgetsneakers/com...,NaN,2022-08-01 06:43:46,NaN,2022-08-01 06:43:46,newbalance